---
- hosts: all 
  gather_facts: yes
  become: true

  tasks: 

  - name: install apache and php
    apt:
      name: 
        - "{{ apache_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution is defined and ansible_distribution == "Ubuntu"
  
  - name: install apache and php
    dnf:
     name:
       - "{{ php_package }}"
     state: latest
     update_cache: yes
    when: ansible_distribution is defined and ansible_distribution == "CentOS"
